controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: / 
    controller: App\Controller\LoginController::index

signup:
    path: /signup
    controller: App\Controller\SignupController::index

logout:
    path: "/logout"
    controller: App\Controller\LoginController::logout

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

systeme:
    path: /systeme
    controller: App\Controller\SystemeController::index

fabricant:
    path: /fabricant
    controller: App\Controller\FabricantController::index
appareil:
    path: /appareil
    controller: App\Controller\AppareilController::index
register:
    path: /register
    controller: App\Controller\RegisterController::index